const landingFaculties = [
  {
    id: {
      $oid: "6892b2e76a11dad8e370fffd",
    },
    name: "Mahbubul Alam Majumdar",
    initial: "MAM",
    photo: "/mam.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [
      {
        user1: 3,
      },
      {
        user2: 1,
      },
      {
        U1: 5,
      },
    ],
    comments: [
      {
        user1: "good",
      },
      {
        user2: "best",
      },
    ],
  },
  {
    id: {
      $oid: "6892b41e6a11dad8e371002c",
    },
    name: "Dr. Sadia Hamid Kazi",
    initial: "SKZ",
    photo: "/skz.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6892b5266a11dad8e371005f",
    },
    name: "Dr. Mohammad Kaykobad",
    initial: "KYK",
    photo: "/kyk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6892ba186a11dad8e37100c4",
    },
    name: "Dr. Chowdhury Mofizur Rahman",
    initial: "CMR",
    photo: "/cmr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895b7be115d47b7329036a0",
    },
    name: "Matin Saad Abdullah",
    initial: "MSA",
    photo: "/msa.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895b832115d47b7329036ad",
    },
    name: "Dr. Md. Khalilur Rahman",
    initial: "KHR",
    photo: "/khr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895b9c9115d47b7329036c1",
    },
    name: "Dr. Md. Golam Rabiul Alam",
    initial: "GRA",
    photo: "/gra.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895b9f6115d47b7329036c6",
    },
    name: "Dr. Md Sadek Ferdous",
    initial: "SDF",
    photo: "/sdf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895ba18115d47b7329036cb",
    },
    name: "Dr. Amitabha Chakrabarty",
    initial: "ACH",
    photo: "/ach.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895ba40115d47b7329036d0",
    },
    name: "Dr. Farida Chowdhury",
    initial: "FDC",
    photo: "/fdc.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "6895ba82115d47b7329036d9",
    },
    name: "Dr. Swakkhar Shatabda",
    initial: "SWK",
    photo: "/swk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c93858d91a6e4fa3f4df3",
    },
    name: "Abu Mohammad Khan",
    initial: "AMK",
    photo: "/amk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c93aa8d91a6e4fa3f4df8",
    },
    name: "Dr. Taiabul Haque",
    initial: "TLQ",
    photo: "/tlq.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c93c78d91a6e4fa3f4dfd",
    },
    name: "Dr. Muhammad Nur Yanhaona",
    initial: "MNY",
    photo: "/mny.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c93eb8d91a6e4fa3f4e02",
    },
    name: "Dr. Md. Ashraful Alam",
    initial: "ASA",
    photo: "/asa.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c94138d91a6e4fa3f4e07",
    },
    name: "Dr. Muhammad Iqbal Hossain",
    initial: "MIH",
    photo: "/mih.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c94448d91a6e4fa3f4e0c",
    },
    name: "Dr. Farig Yousuf Sadeque",
    initial: "FYS",
    photo: "/fys.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [
      {
        U1: 5,
      },
    ],
    comments: [
      {
        U1: "Best",
      },
    ],
  },
  {
    id: {
      $oid: "689c95d78d91a6e4fa3f4e1a",
    },
    name: "Mr. Annajiat Alim Rasel",
    initial: "AAR",
    photo: "/aar.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c966b8d91a6e4fa3f4e20",
    },
    name: "Md. Tawhid Anwar",
    initial: "TAW",
    photo: "/taw.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c97398d91a6e4fa3f4e32",
    },
    name: "Md. Saiful Islam",
    initial: "MSI",
    photo: "/msi.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "689c97718d91a6e4fa3f4e37",
    },
    name: "Md. Imran Bin Azad",
    initial: "MIBA",
    photo: "/miba.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a22e8881b5bef606fba77a",
    },
    name: "Mr. Moin Mostakim",
    initial: "MMM",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2320581b5bef606fba790",
    },
    name: "Mr. Rubayat Ahmed Khan",
    initial: "RAK",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2322881b5bef606fba794",
    },
    name: "Ms. Mehnaz Seraj",
    initial: "SRJ",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2324a81b5bef606fba798",
    },
    name: "Sowmitra Das",
    initial: "SDAS",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2326981b5bef606fba79c",
    },
    name: "Najeefa Nikhat Choudhury",
    initial: "NNC",
    photo: "/nnc.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a233c381b5bef606fba7a8",
    },
    name: "Mahrin Tasfe",
    initial: "MTF",
    photo: "/mtf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2340e81b5bef606fba7ad",
    },
    name: "Dr. Aniqua Nusrat Zereen",
    initial: "AQZ",
    photo: "/aqz.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2344281b5bef606fba7b2",
    },
    name: "Mr. Md. Tanzim Reza",
    initial: "TRZ",
    photo: "/trz.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2348081b5bef606fba7b7",
    },
    name: "Ms. Tasnim Ferdous",
    initial: "TNMF",
    photo: "/tnmf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a234d681b5bef606fba7bc",
    },
    name: "Mr. Rafeed Rahman",
    initial: "RRH",
    photo: "/rrh.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2352881b5bef606fba7c1",
    },
    name: "Dewan Ziaul Karim",
    initial: "DZK",
    photo: "/dzk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a2357781b5bef606fba7c6",
    },
    name: "Md. Saiful Bari Siddiqui",
    initial: "SDQ",
    photo: "/sdq.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32120b428a1dcd0fd2596",
    },
    name: "Shoaib Ahmed Dipu",
    initial: "DPU",
    photo: "/dpu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32176b428a1dcd0fd259b",
    },
    name: "Ahmed Mahir Ruhan",
    initial: "ADU",
    photo: "/adu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a321c8b428a1dcd0fd25a0",
    },
    name: "Afroza Akther",
    initial: "AFA",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3221ab428a1dcd0fd25a4",
    },
    name: "Md. Asif Haider",
    initial: "AHF",
    photo: "/ahf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32263b428a1dcd0fd25a9",
    },
    name: "Md. Ahasanul Alam",
    initial: "AHU",
    photo: "/ahu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a322afb428a1dcd0fd25ae",
    },
    name: "Md Abu Ibrahim Iqra",
    initial: "AIB",
    photo: "/aib.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32709b428a1dcd0fd25c3",
    },
    name: "Mr. Abid Jahan Apon",
    initial: "AJA",
    photo: "/aja.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32723b428a1dcd0fd25c6",
    },
    name: "Akib Anjum",
    initial: "AKJ",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3275ab428a1dcd0fd25c8",
    },
    name: "Mr. Abdullah Al Nakib",
    initial: "ANK",
    photo: "/ank.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a327d1b428a1dcd0fd25cb",
    },
    name: "Anika Priodorshinee Mrittika",
    initial: "APM",
    photo: "/apm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a327e1b428a1dcd0fd25ce",
    },
    name: "Aniqa Tabassum",
    initial: "AQT",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a327f8b428a1dcd0fd25d0",
    },
    name: "Mr. Md. Aquib Azmain",
    initial: "AQU",
    photo: "/aqu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3282db428a1dcd0fd25d3",
    },
    name: "Ayman Rasheed",
    initial: "ARD",
    photo: "/ard.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32846b428a1dcd0fd25d6",
    },
    name: "Arif Shakil",
    initial: "ARF",
    photo: "/arf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3287db428a1dcd0fd25d9",
    },
    name: "Mohammed Ashfaqul Haque",
    initial: "AFQ",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3289db428a1dcd0fd25db",
    },
    name: "Ateya Ahmed Subarna",
    initial: "ATY",
    photo: "/aty.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a328bcb428a1dcd0fd25de",
    },
    name: "Avinandan Banerjee",
    initial: "AVB",
    photo: "/avb.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a328f1b428a1dcd0fd25e1",
    },
    name: "Ariyan Hossain",
    initial: "AYO",
    photo: "/ayo.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32930b428a1dcd0fd25e4",
    },
    name: "Mohammad Badrul Hossain",
    initial: "BDH",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32975b428a1dcd0fd25e6",
    },
    name: "Mr. Dibyo Fabian Dofadar",
    initial: "DFD",
    photo: "/dfd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32997b428a1dcd0fd25e9",
    },
    name: "Muhammad Ehsanul Kader",
    initial: "EHD",
    photo: "/ehd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a1db428a1dcd0fd25ec",
    },
    name: "Ehtashamul Haque",
    initial: "EHQ",
    photo: "/ehq.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a2cb428a1dcd0fd25ef",
    },
    name: "Farden Ehsan Khan",
    initial: "FEK",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a41b428a1dcd0fd25f1",
    },
    name: "Md. Fatin Ishraq Faruqui",
    initial: "FFR",
    photo: "/ffr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a5ab428a1dcd0fd25f4",
    },
    name: "Md. Fakhruddin Gazzali",
    initial: "FGZ",
    photo: "/fgz.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a75b428a1dcd0fd25f7",
    },
    name: "Fatiha Ishrar Chowdhury",
    initial: "FIC",
    photo: "/fic.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32a8db428a1dcd0fd25fa",
    },
    name: "Fardin Zubair Nafis",
    initial: "FZN",
    photo: "/fzn.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32aa1b428a1dcd0fd25fd",
    },
    name: "Mr. Sheikh Araf Noshin",
    initial: "HFN",
    photo: "/hfn.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ab6b428a1dcd0fd2600",
    },
    name: "Ipshita Bonhi Upoma",
    initial: "IBU",
    photo: "/ibu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ad0b428a1dcd0fd2603",
    },
    name: "Md. Khaliduzzaman Khan Samrat",
    initial: "KDZM",
    photo: "/kdzm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32aebb428a1dcd0fd2606",
    },
    name: "Kaniz Fatema Supti",
    initial: "KFP",
    photo: "/kfp.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32b0eb428a1dcd0fd2609",
    },
    name: "Kabbya Kantam Patwary",
    initial: "KKP",
    photo: "/kkp.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32b1fb428a1dcd0fd260c",
    },
    name: "Ms. Khondoker Nazia Iqbal",
    initial: "KNI",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32b3bb428a1dcd0fd260e",
    },
    name: "Kazi Kamruzzaman Rabbi",
    initial: "KZMN",
    photo: "/kzmn.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32b4ab428a1dcd0fd2611",
    },
    name: "Labib Hasan Khan",
    initial: "LBBH",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32b59b428a1dcd0fd2613",
    },
    name: "Marshia Nujhat",
    initial: "MAU",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32c88b428a1dcd0fd2615",
    },
    name: "Sabiha Hasan Mim",
    initial: "MBM",
    photo: "/mbm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ca0b428a1dcd0fd2618",
    },
    name: "Mohammad Fahim",
    initial: "MDF",
    photo: "/mdf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32cb6b428a1dcd0fd261b",
    },
    name: "Mehedi Hasan Emo",
    initial: "MHDE",
    photo: "/mhde.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32cceb428a1dcd0fd261e",
    },
    name: "Mushfique Nasir Probor",
    initial: "MNP",
    photo: "/mnp.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32cdbb428a1dcd0fd2621",
    },
    name: "Mr. Md. Tanvir Arafat",
    initial: "MTT",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32cf1b428a1dcd0fd2623",
    },
    name: "Mr. Md. Shamim Mia",
    initial: "MSMA",
    photo: "/msma.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d09b428a1dcd0fd2626",
    },
    name: "Md. Moynul Asik Moni",
    initial: "MOM",
    photo: "/mom.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d1eb428a1dcd0fd2629",
    },
    name: "Mohammad Nuwaisir Rahman",
    initial: "MNW",
    photo: "/mnw.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d31b428a1dcd0fd262c",
    },
    name: "A B M Muntasir Rahman",
    initial: "MUNR",
    photo: "/munr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d40b428a1dcd0fd262f",
    },
    name: "Sumonta Nandy Amit",
    initial: "NAN",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d4cb428a1dcd0fd2631",
    },
    name: "NIRJHOR DATTA",
    initial: "NDT",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d7ab428a1dcd0fd2633",
    },
    name: "Nafis Karim",
    initial: "NFK",
    photo: "/nfk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d88b428a1dcd0fd2636",
    },
    name: "Nazmul Islam",
    initial: "NZU",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32d95b428a1dcd0fd2638",
    },
    name: "Ms. Narzu Tarannum",
    initial: "NTR",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32da0b428a1dcd0fd263a",
    },
    name: "Noshin Nawal",
    initial: "NNL",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32db0b428a1dcd0fd263c",
    },
    name: "Niloy Farhan",
    initial: "NLH",
    photo: "/nlh.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32dc4b428a1dcd0fd263f",
    },
    name: "Partha Bhoumik",
    initial: "PBK",
    photo: "/pbk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32dd7b428a1dcd0fd2642",
    },
    name: "Mr. Purbayan Das",
    initial: "PDS",
    photo: "/pds.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32de7b428a1dcd0fd2645",
    },
    name: "Prithu Mahmud",
    initial: "PMD",
    photo: "/pmd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32dfdb428a1dcd0fd2648",
    },
    name: "Prothito Shovon Majumder",
    initial: "PSMD",
    photo: "/psmd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32e1ab428a1dcd0fd264b",
    },
    name: "Redowanul Akbar",
    initial: "RDW",
    photo: "/rdw.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32e38b428a1dcd0fd264e",
    },
    name: "Mr. Rakin Bin Rabbani",
    initial: "RBR",
    photo: "/rbr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32e4fb428a1dcd0fd2651",
    },
    name: "Md. Rasel Mia",
    initial: "RAS",
    photo: "/ras.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32e63b428a1dcd0fd2654",
    },
    name: "Quazi Ashikur Rahman",
    initial: "QUZA",
    photo: "/quza.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32e90b428a1dcd0fd2657",
    },
    name: "Imran Zahid",
    initial: "RHD",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32eaab428a1dcd0fd2659",
    },
    name: "Mohammad Rakibul Hasan Mahin",
    initial: "RKBM",
    photo: "/rkbm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ebeb428a1dcd0fd265c",
    },
    name: "Raisul Kabir News",
    initial: "RKN",
    photo: "/rkn.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ecfb428a1dcd0fd265f",
    },
    name: "Rafiad Sadat Shahir",
    initial: "RSS",
    photo: "/rss.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32ee1b428a1dcd0fd2662",
    },
    name: "Md. Sabbir Ahmed",
    initial: "SBB",
    photo: "/sbb.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32efab428a1dcd0fd2665",
    },
    name: "Saadat Rafid Ahmed",
    initial: "SADF",
    photo: "/sadf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f18b428a1dcd0fd2668",
    },
    name: "Sadif Ahmed",
    initial: "SADA",
    photo: "/sada.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f33b428a1dcd0fd266b",
    },
    name: "Rifa Tasfiya",
    initial: "RTF",
    photo: "/rtf.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f4ab428a1dcd0fd266e",
    },
    name: "Sk. Sabit Bin Mosaddek",
    initial: "SBDK",
    photo: "/sbdk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f5eb428a1dcd0fd2671",
    },
    name: "Md Sabbir Hossain",
    initial: "SBHN",
    photo: "/sbhn.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f74b428a1dcd0fd2674",
    },
    name: "Ms. Fateha Jannat Printia",
    initial: "FJP",
    photo: "/fjp.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a32f80b428a1dcd0fd2677",
    },
    name: "Mr. Shadman Shahriar",
    initial: "SDS",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3329fb428a1dcd0fd267f",
    },
    name: "Shomen Kundu",
    initial: "SDU",
    photo: "/sdu.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a332afb428a1dcd0fd2682",
    },
    name: "Asif Shahriar",
    initial: "SHAH",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a332c3b428a1dcd0fd2684",
    },
    name: "K. M. Shadman Wadith",
    initial: "SHDM",
    photo: "/shdm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a332e1b428a1dcd0fd2687",
    },
    name: "Shahriar Hasan Mickey",
    initial: "SHMK",
    photo: "/shmk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a332fab428a1dcd0fd268a",
    },
    name: "Sukarna Sarker",
    initial: "SUE",
    photo: "/sue.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33312b428a1dcd0fd268d",
    },
    name: "Mr. Shakir Rouf",
    initial: "SRU",
    photo: "/sru.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3336db428a1dcd0fd2693",
    },
    name: "Sahib Kowsar",
    initial: "SKW",
    photo: "/skw.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33385b428a1dcd0fd2696",
    },
    name: "Mr. Shahriar Rahman Rana",
    initial: "SHRR",
    photo: "/shrr.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3339cb428a1dcd0fd2699",
    },
    name: "Md. Sultanul Arifin",
    initial: "SULT",
    photo: "/sult.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a333b4b428a1dcd0fd269c",
    },
    name: "Swattic Ghose",
    initial: "SWG",
    photo: "/swg.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a333cab428a1dcd0fd269f",
    },
    name: "Showvik Biswas",
    initial: "SWV",
    photo: "/swv.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a333edb428a1dcd0fd26a4",
    },
    name: "Mr. Md. Shazid Bin Mahbub",
    initial: "SZD",
    photo: "/szd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a333feb428a1dcd0fd26a8",
    },
    name: "Mr. Tamkin Mahmud Tan",
    initial: "TMD",
    photo: "/tmd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33417b428a1dcd0fd26ab",
    },
    name: "Mohammad Tahsin Alam",
    initial: "THL",
    photo: "/thl.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a3342eb428a1dcd0fd26ae",
    },
    name: "Tasnim Ahsan Prome",
    initial: "TAP",
    photo: "/tap.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33440b428a1dcd0fd26b1",
    },
    name: "Sazzadul Islam",
    initial: "SZZ",
    photo: "/szz.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33455b428a1dcd0fd26b4",
    },
    name: "Tanvir Muntakim Tonoy",
    initial: "TMY",
    photo: "/tmy.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33471b428a1dcd0fd26b7",
    },
    name: "Mr. Mirza Md. Tanjim Shorif Mugdho",
    initial: "TSM",
    photo: "/tsm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33489b428a1dcd0fd26ba",
    },
    name: "Towshik Anam Taj",
    initial: "TWK",
    photo: "/twk.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a334a7b428a1dcd0fd26be",
    },
    name: "Umme Jannat Taposhi",
    initial: "UJT",
    photo: "/ujt.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a334bbb428a1dcd0fd26c1",
    },
    name: "Mr. Zaber Mohammad",
    initial: "ZMD",
    photo: "/zmd.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a334d5b428a1dcd0fd26c4",
    },
    name: "Mr. Syed Zamil Hasan Shoumo",
    initial: "ZHS",
    photo: "",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a334e8b428a1dcd0fd26c6",
    },
    name: "Utsab Saha",
    initial: "UTS",
    photo: "/uts.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33500b428a1dcd0fd26c9",
    },
    name: "Tasnim Sobhan Upoma",
    initial: "UPM",
    photo: "/upm.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a33517b428a1dcd0fd26cc",
    },
    name: "Zayed Humayun",
    initial: "ZYH",
    photo: "/zyh.png",
    department: "CSE",
    courses: [],
    __v: 0,
    stars: [],
    comments: [],
  },
  {
    id: {
      $oid: "68a45229660b98896dbb398e",
    },
    name: "Anika Afrin",
    initial: "AAF",
    photo: "/aaf.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a45240660b98896dbb3990",
    },
    name: "Ayesha Siddika",
    initial: "ADD",
    photo: "/add.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a45257660b98896dbb3992",
    },
    name: "Muhammad Abdur Rahman",
    initial: "ADR",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a45269660b98896dbb3994",
    },
    name: "Asif Hasan Chowdhury",
    initial: "AHC",
    photo: "/ahc.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a880b88a82ecf62596e156",
    },
    name: "Ahmed Akib Jawad Karim",
    initial: "AJK",
    photo: "/ajk.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8814d8a82ecf62596e158",
    },
    name: "Abdullah Khondoker",
    initial: "AKDR",
    photo: "/akdr.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a881f38a82ecf62596e15a",
    },
    name: "Anindita Labonno",
    initial: "ALB",
    photo: "/alb.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a882138a82ecf62596e15c",
    },
    name: "Ms. Anika Tasnim",
    initial: "ANT",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8822e8a82ecf62596e15e",
    },
    name: "A S M Nasim Khan",
    initial: "ASMN",
    photo: "/asmn.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8824e8a82ecf62596e160",
    },
    name: "Atanu Roy",
    initial: "ART",
    photo: "/art.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a882868a82ecf62596e162",
    },
    name: "Abu Obaida Hasme",
    initial: "AOH",
    photo: "/aoh.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a882a38a82ecf62596e164",
    },
    name: "Md. Anonto Shuvo",
    initial: "ANV",
    photo: "/anv.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a882c48a82ecf62596e166",
    },
    name: "Mirza Azwad Wakil",
    initial: "AWK",
    photo: "/awk.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a882e48a82ecf62596e168",
    },
    name: "Atonu Roy Chowdhury",
    initial: "CARC",
    photo: "/carc.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883078a82ecf62596e16a",
    },
    name: "Mr. MD FARDIN RAHMAN AMI",
    initial: "FDM",
    photo: "/fdm.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883238a82ecf62596e16c",
    },
    name: "Fardin Zaman",
    initial: "FDZ",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883378a82ecf62596e16e",
    },
    name: "Md. Mahadi Hasan",
    initial: "HAS",
    photo: "/has.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883608a82ecf62596e170",
    },
    name: "M. Shafiul Alam",
    initial: "FUL",
    photo: "/ful.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883868a82ecf62596e172",
    },
    name: "Md. Saif Mokarrom",
    initial: "FMK",
    photo: "/fmk.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883a78a82ecf62596e174",
    },
    name: "Farhan Faruk",
    initial: "FFU",
    photo: "/ffu.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883c38a82ecf62596e176",
    },
    name: "Mr. Hamim Ibne Nasim",
    initial: "HBN",
    photo: "/hbn.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a883eb8a82ecf62596e178",
    },
    name: "Mir Hamidul Hussain",
    initial: "HMH",
    photo: "/hmh.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884168a82ecf62596e17a",
    },
    name: "Md. Irtiza Hossain",
    initial: "IRZ",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8843f8a82ecf62596e17c",
    },
    name: "Dr. Jannatun Noor Mukta",
    initial: "JNM",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884578a82ecf62596e17e",
    },
    name: "Ms. Lamiah Israt",
    initial: "LMI",
    photo: "/lmi.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884a58a82ecf62596e180",
    },
    name: "Kaji Sajjad Hossain",
    initial: "KSJ",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884bf8a82ecf62596e182",
    },
    name: "Kushol Roy Pritom",
    initial: "KRP",
    photo: "/krp.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884e08a82ecf62596e184",
    },
    name: "Ms. Kefaya Benta Shahnoor",
    initial: "KBS",
    photo: "/kbs.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a884f98a82ecf62596e186",
    },
    name: "MD ASIF",
    initial: "MAF",
    photo: "/maf.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885148a82ecf62596e188",
    },
    name: "Mirza Abdullah Al Noman",
    initial: "MAO",
    photo: "/mao.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8852f8a82ecf62596e18a",
    },
    name: "Mahjabin Chowdhury",
    initial: "MCW",
    photo: "/mcw.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885458a82ecf62596e18c",
    },
    name: "Abu Musa Al Ashary",
    initial: "MHY",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885578a82ecf62596e18e",
    },
    name: "Md. Imtiaj Hossain",
    initial: "MTJ",
    photo: "/mtj.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8858a8a82ecf62596e190",
    },
    name: "Mohammad Sayeem Sadat Hossain",
    initial: "MSDH",
    photo: "/msdh.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8859e8a82ecf62596e192",
    },
    name: "Mr. Monzur Murshed Muhammad",
    initial: "MOZR",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885b18a82ecf62596e194",
    },
    name: "Monirul Haque",
    initial: "MLH",
    photo: "/mlh.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885d28a82ecf62596e196",
    },
    name: "Md. Muhtasim Mahmud",
    initial: "MTU",
    photo: "/mtu.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a885ef8a82ecf62596e198",
    },
    name: "Mehnaz Ara Fazal",
    initial: "MZFZ",
    photo: "/mzfz.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8861a8a82ecf62596e19a",
    },
    name: "Ahmed Mayeesha Reza Agomoni",
    initial: "MZG",
    photo: "/mzg.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a886398a82ecf62596e19c",
    },
    name: "Maazin Munawar",
    initial: "MZW",
    photo: "/mzw.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a886688a82ecf62596e19e",
    },
    name: "Noshin Tabassum",
    initial: "NTB",
    photo: "/ntb.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8867e8a82ecf62596e1a0",
    },
    name: "Md Nafiz Ishtiaque Mahee",
    initial: "NQM",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8868c8a82ecf62596e1a2",
    },
    name: "Namira Mustafiz Pranty",
    initial: "NMP",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a886988a82ecf62596e1a4",
    },
    name: "Nafiz Imtiaz Rafin",
    initial: "NFF",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a886d98a82ecf62596e1a6",
    },
    name: "Naima Tahsin Nodi",
    initial: "NTN",
    photo: "/ntn.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a886f88a82ecf62596e1a8",
    },
    name: "Nur Mohammad Shaon",
    initial: "NUR",
    photo: "/nur.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887118a82ecf62596e1aa",
    },
    name: "Nowshin Tabassum",
    initial: "NWT",
    photo: "/nwt.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8873b8a82ecf62596e1ac",
    },
    name: "Pollock Nag",
    initial: "PLN",
    photo: "/pln.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887728a82ecf62596e1ae",
    },
    name: "MD Rifat Alam Pomil",
    initial: "PML",
    photo: "/pml.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887ae8a82ecf62596e1b0",
    },
    name: "Rantu Das",
    initial: "RDS",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887bb8a82ecf62596e1b2",
    },
    name: "Mohammed Radoan",
    initial: "RAO",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a896125dcea83a08eced5b",
    },
    name: "Mr. Pratick Roy Chowdhuruy",
    initial: "PRC",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a896c45dcea83a08eced5e",
    },
    name: "Shadmin Sultana",
    initial: "SDL",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887d38a82ecf62596e1b4",
    },
    name: "Rafid Ahnaf",
    initial: "RFF",
    photo: "/rff.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a887f78a82ecf62596e1b6",
    },
    name: "Md. Rafatul Haq",
    initial: "RFQ",
    photo: "/rfq.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8880e8a82ecf62596e1b8",
    },
    name: "Riazul Islam Rifat",
    initial: "RZR",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8881e8a82ecf62596e1ba",
    },
    name: "Sadiul Arefin Rafi",
    initial: "SLAR",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8882f8a82ecf62596e1bc",
    },
    name: "Sajid Imam Mahir",
    initial: "SJM",
    photo: "/sjm.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888598a82ecf62596e1be",
    },
    name: "Sheikh Iftekhar Ahmed",
    initial: "SEF",
    photo: "/sef.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888848a82ecf62596e1c0",
    },
    name: "Sanjida Tasnim",
    initial: "SDTS",
    photo: "/sdts.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888a28a82ecf62596e1c2",
    },
    name: "Sheikh Samiul Kadir",
    initial: "SMKD",
    photo: "/smkd.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888d18a82ecf62596e1c4",
    },
    name: "Samiur Rahman",
    initial: "SMUR",
    photo: "/smur.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888e78a82ecf62596e1c6",
    },
    name: "Syeda Sumaiya Tasneem",
    initial: "SSMT",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a888f98a82ecf62596e1c8",
    },
    name: "Mr. Sifat Tanvir",
    initial: "STV",
    photo: "/stv.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889138a82ecf62596e1ca",
    },
    name: "Tasnia Juha",
    initial: "TJH",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889208a82ecf62596e1cc",
    },
    name: "Tahsin Tanim Ramisha",
    initial: "THR",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a8894c8a82ecf62596e1ce",
    },
    name: "Tarvir Anjum Aditto",
    initial: "TAV",
    photo: "/tav.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889648a82ecf62596e1d0",
    },
    name: "Sumaiya",
    initial: "SUI",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889758a82ecf62596e1d2",
    },
    name: "Sk. Atik Tajwar Sihan",
    initial: "TJW",
    photo: "/tjw.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889918a82ecf62596e1d4",
    },
    name: "Tanjim Reza",
    initial: "TNZ",
    photo: "/tnz.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889a98a82ecf62596e1d6",
    },
    name: "Tasneem Mazhar",
    initial: "TSE",
    photo: "/tse.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a889db8a82ecf62596e1d8",
    },
    name: "Umaiya Ahmed Maisha",
    initial: "UMS",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a88a008a82ecf62596e1da",
    },
    name: "Ihzaz Abrar Sadik",
    initial: "ZAZ",
    photo: "/zaz.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a88a2c8a82ecf62596e1dc",
    },
    name: "Yasmin Nadia",
    initial: "YND",
    photo: "/ynd.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a88a478a82ecf62596e1de",
    },
    name: "Md.Waseq Alauddin Alvi",
    initial: "WLV",
    photo: "/wlv.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a88a5a8a82ecf62596e1e0",
    },
    name: "Waleed Bin Habib Khan",
    initial: "WBH",
    photo: "",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
  {
    id: {
      $oid: "68a88a6f8a82ecf62596e1e2",
    },
    name: "Md. Zayed Bin Zahir Arju",
    initial: "ZBH",
    photo: "/zbh.png",
    department: "CSE",
    courses: [],
    stars: [],
    comments: [],
    __v: 0,
  },
];
export default landingFaculties;
